{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-security-jwt-webflux-autoconfigure",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-jwt-webflux-autoconfigure-0.2.0-plain.jar",
          "url": "spring-security-jwt-webflux-autoconfigure-0.2.0-plain.jar",
          "size": 4478,
          "sha512": "00ede5d0e8f6c73d67837b227036abbdec6c5a148bf1c7e410b6f391322558cdaab062458cef84bf6d04823ace247439a4a088a1134f35334aa667bcc17e50ef",
          "sha256": "ee3d5a99559b76f530cf319cdd94024602f7c1221fe9dcf5feab50b333109ce7",
          "sha1": "fec57eb439b19b0c1a10fc3e7b88f1a01f01f0df",
          "md5": "1da2ecb70f9cb11986ed06bd1179f6ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security"
        }
      ],
      "files": [
        {
          "name": "spring-security-jwt-webflux-autoconfigure-0.2.0-plain.jar",
          "url": "spring-security-jwt-webflux-autoconfigure-0.2.0-plain.jar",
          "size": 4478,
          "sha512": "00ede5d0e8f6c73d67837b227036abbdec6c5a148bf1c7e410b6f391322558cdaab062458cef84bf6d04823ace247439a4a088a1134f35334aa667bcc17e50ef",
          "sha256": "ee3d5a99559b76f530cf319cdd94024602f7c1221fe9dcf5feab50b333109ce7",
          "sha1": "fec57eb439b19b0c1a10fc3e7b88f1a01f01f0df",
          "md5": "1da2ecb70f9cb11986ed06bd1179f6ae"
        }
      ]
    }
  ]
}
